### ISSUE TITLE
Bug: SSL Cert needs to send two commands for  *.domain and .domain

### ISSUE THREAD

**Issue by SahilKalra98** [garageScript/myProxy#102]

**Comment by Wolfy64** [comment]
@SahilKalra98 What do mean by two command ? 
Could you explain your steps ? 
I will look at it tonight 🙂

**Comment by songz** [comment]
Right now, there is 2 `-d` options. Only the first certificate gets generated. We need 2 sets of certificates:
1. *.domain.com (wildcard)
2. domain.com (root)
