### ISSUE TITLE
Question about prod.config.js

### ISSUE THREAD

**Issue by Wolfy64** [garageScript/myProxy#128]
Does it make sense for a user that not use `pm2` to have this file? 
I think this file should not be on Github only on the server same for `deploy.sh`. 
**OR**
We can add `pm2` as dependency and change `npm start` to run it ?

```
module.exports = {
  apps: [
    {
      name: 'myProxy-prod',
      script: './build/app.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_production: {
        NODE_ENV: 'production', 
        PORT: 3000, // Should be setup with Process.env.PORT
        ADMIN: '123' // Should be setup with Process.env.ADMIN
      },
    },
  ],
}
```

**Comment by songz** [comment]
who is `user` in your question?

1. If they are contributors, then they wouldn't use pm2. They are probably using nodemon or supervisor.
2. If they are our end users, then they shouldn't care what is being used to run the proxy.
