### ISSUE TITLE
Remove Admin path/Refactor

### ISSUE THREAD

**Issue by SahilKalra98** [garageScript/myProxy#262]

**Comment by songz** [comment]
# ADMIN paths
Only admins should be able to manage:
`/accessTokens`
`/sshKeys`

# User paths
`/`
`/mappings`

# Publicly Accessible
`/login`

**Comment by hwong0305** [comment]
# Updated Logic

# ADMIN paths
Only admins should be able to manage:
`/accessTokens`
`/admin`

# User paths
`/`
`/mappings`
`/sshKeys`

# Publicly Accessible
`/login`

API routers must handle theses accesses accordingly, which means admin only API routes must have `api/admin` prefix and require `isAdmin` in `req.user` object.
