### ISSUE TITLE
Upgrade setup script to install node version 12.

### ISSUE THREAD

**Issue by songz** [garageScript/myProxy#265]
**Is your feature request related to a problem? Please describe.**
Currently, `setup.sh` sets up nodeJS version 8. Unfortunately, version 8 causes issues with React, causing wrong packages to be installed.

**Describe the solution you'd like**
Setup script should install version 12 (currently latest). With with the following command:
```
sudo apt-get install curl
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
```
Step 1 from [this source](https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/)

Node 12 should also come with `npm`, so we will not be needing the line that installs `npm`

**Comment by hwong0305** [comment]
This needs an additional command "sudo apt-get install -y nodejs" to tell the server to install node. 

The curl command only downloads the files from the repo but does not install it.
