### ISSUE TITLE
Ability to download logs

### ISSUE THREAD

**Issue by songz** [garageScript/myProxy#288]
**Is your feature request related to a problem? Please describe.**
When an issue is happening with my app, I would like to be able to view my server logs.

**Describe the solution you'd like**
Beside each app, I have an icon to down logs.

**Comment by songz** [comment]
User 1 request
![Screen Shot 2019-12-06 at 5 04 06 PM](https://user-images.githubusercontent.com/686933/70366200-7652b600-184a-11ea-8644-973ef958384c.png)

**Comment by hwong0305** [comment]
Resources for logs:

https://stackoverflow.com/questions/13106096/stream-files-in-node-express-to-client
Log files: https://stackoverflow.com/questions/55828017/what-is-the-default-location-of-pm2-log-files
