### ISSUE TITLE
Subdomains don't appear on domain list

### ISSUE THREAD

**Issue by joshgreenwell** [garageScript/myProxy#326]
**Describe the bug**
On the My Proxy page, no subdomains are being listed although I can see that they are running when I check pm2 on the server.

**To Reproduce**
1. Go to '/admin'
2. Click on 'My Proxy'
3. See error

**Expected behavior**
To see my subdomains

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 78.0.3904.108

**Additional context**
Just updated to the newest version

**Comment by Wolfy64** [comment]
Look like this issue has been fixed so I close it 🙂
