### ISSUE TITLE
Add xforward headers

### ISSUE THREAD

**Issue by songz** [garageScript/myProxy#363]
**Describe the bug**
In my apps that I deploy with `myProxy`, `request.ip` will **always** be 127.0.0.1 (myProxy's server). 
Expected value: the ip address of the actual requestor.

**To Reproduce**
1. Create an app. 
2. Request handler: `console.log( req.ip ) // 127.0.01`
3. Request handler: `console.log( req.headers['x-forwarded-for'] ) // undefined`

**Expected behavior**
1. `req.headers['x-forwarded-for']` should contain the requestor's IP address

**Screenshots**

![Screen Shot 2020-02-06 at 7 12 31 AM](https://user-images.githubusercontent.com/686933/73950029-190dcc00-48b0-11ea-8739-c8caac29ecdf.png)

**Additional context**
Possible fix:
1. `xfwd` headers when creating proxy: https://github.com/http-party/node-http-proxy

**Comment by hwong0305** [comment]
Closed by #364
