### ISSUE TITLE
Add domain expiration date in /api/admin.ts

### ISSUE THREAD

**Issue by allopez7** [garageScript/myProxy#84]

**Comment by Wolfy64** [comment]
Need more details for this issue. We talk about **Domain name**  expiration and not **SSL** Right?
Within `admin.ts` or `data.db` I can read `"<ssl expiration date will go here>"`.
The acme.sh wiki [12. How to renew the certs](https://github.com/Neilpang/acme.sh#12-how-to-renew-the-certs) said:

> No, you don't need to renew the certs manually. All the certs will be renewed automatically every 60 days.

However I can add the domain expiration date like this
```
    {
      "domain": "hireme.fun",
      "expiration": "<domain expiration date will go here>",
      "provider": "dns_gd"
    },
```
Let me know 🙂

**Comment by songz** [comment]
`No, you don't need to renew the certs manually. All the certs will be renewed automatically every 60 days.`. -> THATS AWESOME. Thankyou for looking into this @Wolfy64 , closing this issue.
